import {
  Menubar,
  MenubarContent,
  MenubarItem,
  MenubarMenu,
  MenubarTrigger,
} from "@/components/ui/menubar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="p-8 max-w-2xl mx-auto">
      <body className={inter.className}>
        <header className="flex mb-8">
          <Menubar>
            <MenubarMenu>
              <MenubarTrigger asChild>
                <Link href="/">Dashboard</Link>
              </MenubarTrigger>
            </MenubarMenu>
            <MenubarMenu>
              <MenubarTrigger>Import</MenubarTrigger>
              <MenubarContent>
                <MenubarItem asChild>
                  <Link href="/import/abn-amro">ABN AMRO</Link>
                </MenubarItem>
                <MenubarItem asChild>
                  <Link href="/import/american-express">American Express</Link>
                </MenubarItem>
              </MenubarContent>
            </MenubarMenu>
          </Menubar>
        </header>
        {children}
      </body>
    </html>
  );
}
